Repository ezen-bentto/react-frontend, pull requests merged in 2025-06, with the labels that each got.

#9 feat: 청년 정책 페이지 router 연결
  public/data/korea-policy-list.json
  public/data/region-policy-list.json
  public/data/seoul-gu-policy-list.json
  public/data/seoul-policy-list.json
  public/vite.svg
  src/main.tsx
  src/pages/Policy/Policy.tsx
  src/pages/Stats/Stats.tsx
  src/routers/AppRouter.tsx
Labels: enhancement, feature

#13 feat : 공모전 크롤링 데이터
  public/data/contests-list.json
Labels: feature

#17 feat : 프론트엔드 로그인,회원가입 페이지
  src/components/shared/Header.tsx
  src/pages/Login/Login.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/SignUp/SignUpCompany.tsx
  src/pages/SignUp/SignUpPersonal.tsx
  src/pages/SignUp/SignUpTypeSelect.tsx
  src/routers/AppRouter.tsx
Labels: feature

#19 fix : list 컴포넌트 작성자 css 수정
  src/components/shared/ListItem.tsx
Labels: fix

#22 feat: top-btn 컴포넌트 구현
  src/components/shared/TopButton.tsx
  src/components/style/topBtn.ts
  src/layouts/MainLayout.tsx
Labels: feature

#23 feat : write 버튼 구현
  index.html
  src/components/shared/TopButton.tsx
  src/components/shared/WriteButton.tsx
  src/components/style/fixedCircleBtn.ts
  src/pages/Home/Home.tsx
Labels: feature

#24 feat : 메인페이지 1차 구현
  public/data/contests-list.json
  src/api/community/content.ts
  src/api/community/delete.ts
  src/api/community/list.ts
  src/components/home/CommunityList.tsx
  src/components/home/ContestSlider.tsx
  src/components/home/Policy.tsx
  src/components/home/PolicySider.tsx
  src/components/home/PopularContestCard.tsx
  src/components/home/PopularContestList.tsx
  src/components/home/SwiperNavBtn.tsx
  src/components/shared/Badge.tsx
  src/components/shared/Card.tsx
  src/components/shared/Header.tsx
  src/components/shared/ListItem.tsx
  src/components/style/badge.ts
  src/components/style/listItem.ts
  src/config/env.ts
  src/pages/Community/CommunityContent.tsx
  src/pages/Community/CommunityList.tsx
  src/pages/Community/CommunityWrite.tsx
  src/pages/Home/Home.tsx
Labels: feature

#27 feat: 마이페이지 기본 구현
  src/api/comment/delete.ts
  src/api/comment/list.ts
  src/api/comment/modify.ts
  src/api/comment/register.ts
  src/api/common/category.ts
  src/api/community/content.ts
  src/api/community/delete.ts
  src/api/community/list.ts
  src/api/community/register.ts
  src/pages/MyPage/MyPage.tsx
Labels: feature

#39 feat : 공모전 페이지 필터 재적용 및 contest json 파일 경량
  public/data/contest.json
  public/data/contest/contest_1.json
  public/data/contest/contest_10.json
  public/data/contest/contest_2.json
  public/data/contest/contest_3.json
  public/data/contest/contest_4.json
  public/data/contest/contest_5.json
  public/data/contest/contest_6.json
  public/data/contest/contest_7.json
  public/data/contest/contest_8.json
  public/data/contest/contest_9.json
  src/api/contest/list.ts
  src/components/shared/Card.tsx
  src/components/shared/Fillter.tsx
  src/components/shared/Pagination.tsx
  src/components/shared/SearchInput.tsx
  src/features/contest/useGetList.ts
  src/pages/Contest/ContestList.tsx
Labels: feature

#41 feat : 공모전 상세페이지 구현
  public/data/contest.json
  src/App.css
  src/api/community/list.ts
  src/api/community/modify.ts
  src/components/contest/DetailContent.tsx
  src/components/contest/DetailInfo.tsx
  src/components/style/button.ts
  src/index.css
  src/pages/Community/CommunityContent.tsx
  src/pages/Community/CommunityList.tsx
  src/pages/Community/CommunityWrite.tsx
  src/pages/Contest/ContestDetail.tsx
  src/routers/AppRouter.tsx
Labels: feature

#42 feat : 메인 페이지 공모전 데이터 방식 변경, 커뮤니티 리스트
  src/components/home/CommunityList.tsx
  src/features/community/useGetList.ts
  src/features/contest/store.ts
  src/pages/Home/Home.tsx
Labels: feature

#49 fix : 메인페이지 모바일 대응 수정
  src/components/home/PopularContestCard.tsx
  src/components/shared/Header.tsx
  src/components/style/header.ts
  src/main.tsx
Labels: fix

#63 feat : 메인 배너 교체 및 header active 효과 추가
  public/images/banner_1.png
  src/components/home/MainBanner.tsx
  src/components/shared/Button.tsx
  src/components/shared/Card.tsx
  src/components/shared/Fillter.tsx
  src/components/shared/FilterGroupSection.tsx
  src/components/shared/Header.tsx
  src/components/shared/SearchInput.tsx
  src/components/shared/Title.tsx
  src/index.css
Labels: feature

#66 feat: 청년 정책 filter 기능 구현
  public/data/korea-policy-list.json
  public/data/region-policy-list.json
  public/data/seoul-gu-policy-list.json
  public/data/seoul-policy-list.json
  src/components/shared/Fillter.tsx
  src/components/shared/ListItem.tsx
  src/components/style/listItem.ts
  src/features/Policy/FilterGroupSection.tsx.tsx
  src/features/Policy/TreeFilterGroupSection.tsx
  src/features/Policy/api.ts
  src/features/Policy/clearRegion.ts
  src/features/Policy/filters.ts
  src/features/Policy/getPolicyLink.ts
  src/features/Policy/store.ts
  src/pages/Policy/Policy.tsx
  src/pages/Policy/PolicyList.tsx
Labels: feature

#67 fix: filter 자식 요소 관련 수정 사항 및 lint 에러 해결
  src/components/shared/Fillter.tsx
  src/features/Policy/FilterGroupSection.tsx.tsx
  src/features/Policy/TreeFilterGroupSection.tsx
  src/pages/Policy/Policy.tsx
  src/pages/Policy/PolicyList.tsx
Labels: feature

#68 feat : 정책 list 링크 구현
  src/components/home/PolicySider.tsx
Labels: feature

#69 feat: 청년 정책 검색, 페이지네이션 기능 추가
  src/features/Policy/TreeFilterGroupSection.tsx
  src/features/Policy/api.ts
  src/features/Policy/filterGroups.ts
  src/pages/Policy/Policy.tsx
Labels: feature

#73 feat : 공모전 bookmark 기능 구현
  src/api/contest/list.ts
  src/components/contest/DetailContent.tsx
  src/components/contest/DetailInfo.tsx
  src/pages/Stats/Stats.tsx
  src/routers/AppRouter.tsx
Labels: feature

#76 feat : 북마크 cnt 조회 및 tanstack query 적용
  src/api/contest/list.ts
  src/components/contest/DetailInfo.tsx
  src/features/contest/useBookmark.ts
  src/features/contest/useGetList.ts
  src/types/contestType.ts
Labels: feature

#78 feat : 북마크 tanstack query 낙관적 업데이트 추가
  src/components/contest/DetailInfo.tsx
  src/features/contest/useBookmark.ts
Labels: feature

#80 style : 메인 배너 text color 수정
  src/components/home/MainBanner.tsx
  src/index.css
Labels: feature

#83 fix : 북마크 API 분리
  src/api/contest/list.ts
  src/components/contest/DetailInfo.tsx
  src/components/shared/Header.tsx
  src/features/contest/useBookmark.ts
  src/pages/Contest/ContestDetail.tsx
Labels: fix

#85 fix : contest-detail 부분 오류
  src/components/shared/Card.tsx
  src/pages/Contest/ContestForm.tsx
  src/store/ContestFormStore.ts
  src/types/contestType.ts
  yarn.lock
Labels: fix

#87 feat : 수정페이지 접근 제한 기능
  src/api/axiosInstance.ts
  src/api/comment/list.ts
  src/api/common/category.ts
  src/api/community/content.ts
  src/api/community/delete.ts
  src/api/community/list.ts
  src/api/community/register.ts
  src/api/contest/listByCategory.ts
  src/api/scrap/toggle.ts
  src/components/shared/ListItem.tsx
  src/pages/Community/CommunityContent.tsx
  src/pages/Community/CommunityList.tsx
  src/pages/Community/CommunityWrite.tsx
  src/pages/Contest/ContestDetail.tsx
  src/pages/Contest/ContestUpdate.tsx
  src/routers/AppRouter.tsx
Labels: fix

#90 feat : 마이페이지 기능
  .eslintrc.json
  public/images/default-avatar.png
  src/api/contest/contestApi.ts
  src/api/contest/list.ts
  src/api/mypage/mypage.ts
  src/components/community/content/Actions.tsx
  src/components/community/content/CommentForm.tsx
  src/components/community/content/CommentItem.tsx
  src/components/community/content/CommentSection.tsx
  src/components/community/content/CountdownBox.tsx
  src/components/community/content/DarkModeToggle.tsx
  src/components/community/content/Details.tsx
  src/components/community/content/Header.tsx
  src/components/community/content/Info.tsx
  src/components/community/list/CommunityGrid.tsx
  src/components/community/list/EmptyState.tsx
  src/components/community/list/FilterSection.tsx
  src/components/community/modal/CommentDeleteModal.tsx
  src/components/community/modal/CommentResultModal.tsx
  src/components/community/modal/PostDeleteModal.tsx
  src/components/community/modal/PostDeleteResultModal.tsx
  src/components/community/modal/SubmitModal.tsx
  src/components/community/write/BaseInfoSection.tsx
  src/components/community/write/CategorySelect.tsx
  src/components/community/write/ContestSelect.tsx
  src/components/community/write/RecruitmentRoleInput.tsx
  src/components/community/write/RequirementInfoSection.tsx
  src/components/community/write/TitleContentInput.tsx
  src/components/community/write/TypeSelector.tsx
  src/components/shared/ListItem.tsx
  src/context/AuthContext.tsx
  src/features/community/communityFormatDate.ts
  src/features/community/useCommunityData.ts
  src/features/community/useCommunityForm.ts
  src/features/community/useCommunityHandlers.ts
  src/features/community/useCommunityList.ts
  src/features/community/useCountdown.ts
  src/features/community/useResponsive.ts
  src/pages/Community/CommunityContent.tsx
  src/pages/Community/CommunityList.tsx
  src/pages/Community/CommunityWrite.tsx
  src/pages/Contest/ContestList.tsx
  src/pages/Login/Login.tsx
  src/pages/MyPage/CompanyMypage.tsx
  src/pages/MyPage/PersonalMypage.tsx
  src/pages/SignUp/SignUpCompany.tsx
  src/types/commentType.ts
  src/types/communityContentType.ts
  src/types/communityListType.ts
  src/types/communityWriteType.ts
  src/types/contestType.ts
  src/types/modalTypes.ts
Labels: feature

#92 feat: favicon 설정
  index.html
  public/assets/icons/jeans_favi.png
Labels: feature

#98 feat : contest image
  src/components/contest/ContestFormTemplate.tsx
  src/components/contest/DetailInfo.tsx
  src/components/shared/Card.tsx
  src/components/shared/FileInput.tsx
  src/pages/Contest/ContestDetail.tsx
  src/pages/Contest/ContestList.tsx
  src/pages/Contest/ContestUpdate.tsx
  src/types/contestType.ts
  src/utils/bufferJsonToBlob.ts
Labels: feature

#104 fix : 마이페이지 태그 오류 수정
  src/api/common/upload.ts
  src/components/community/content/CountdownBox.tsx
  src/components/community/content/Header.tsx
  src/components/community/write/TitleContentInput.tsx
  src/components/shared/ListItem.tsx
  src/features/community/useCommunityList.ts
  src/features/community/useCountdown.ts
  src/pages/Community/CommunityList.tsx
  src/pages/Community/CommunityWrite.tsx
  src/pages/Login/Login.tsx
  src/pages/MyPage/CompanyMypage.tsx
  src/pages/MyPage/PersonalMypage.tsx
  src/pages/SignUp/SignUpCompany.tsx
  src/pages/SignUp/SignUpPersonal.tsx
  src/utils/countDate.ts
Labels: feature

#105 fix : 공모전 크롤링 데이터 리스트 내 태그 표시 수정
  src/components/shared/ListItem.tsx
  src/pages/Community/CommunityWrite.tsx
  src/pages/MyPage/CompanyMypage.tsx
  src/pages/MyPage/PersonalMypage.tsx
  src/types/communityWriteType.ts
Labels: feature

#106 fix : 프론트 배포 오류 문제 수정(ListItem 코드 일부 복원)
  src/components/shared/ListItem.tsx
Labels: feature

#110 fix : 공모전 커뮤니티 불러오기 수정
  src/pages/Contest/ContestDetail.tsx
Labels: fix

#113 fix : 프론트배포 오류 페이지 수정
  src/pages/MyPage/CompanyMypage.tsx
  src/pages/MyPage/PersonalMypage.tsx
Labels: feature
